---

- name: Configure php-fpm pools
  template:
    src: php-fpm.conf.j2
    dest: /etc/php-fpm.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_dict: "{{ php_fpm_pools }}"
  when: php_enable_php_fpm
  notify:
    - restart php-fpm

# Have to use an empty www.conf as a placeholder. If we delete www.conf
# it will be restored the next time the package is updated. No bueno.
- name: Disable default php-fpm pool (www.conf)
  copy:
    src: placeholder.txt
    dest: "{{ php_fpm_config_path }}/www.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: php_fpm_disable_default_pool and php_enable_php_fpm
  notify:
    - restart php-fpm
